#!/bin/bash
#PBS -l select=1:ncpus=40:ngpus=8
#PBS -l pmem=500GB
#PBS -N stress_test_8gpu_8h
#PBS -j oe
#PBS -o stress_test_8gpu_8h.log
#PBS -v CONTAINER_IMAGE=nvcr.io/nvidia/tensorflow:20.02-tf2-py3

cd "$PBS_O_WORKDIR" || exit $?

nvidia-smi

export HOME=/home/users/uat

cd /home/users/uat/scratch
rm -rf stress_test_8gpu_8h
mkdir stress_test_8gpu_8h
pwd
ls
cd stress_test_8gpu_8h
git clone --depth 1 https://github.com/tlkh/mini-dlperf
cd mini-dlperf/tensorflow
bash setup.sh

python3 synthetic_benchmarks/tflop_meter.py --num_gpus 8 --time 43200

nvidia-smi
